"""add delivery

Revision ID: 14c246d6c7d7
Revises: 73f78a8350d4
Create Date: 2025-01-20 04:30:06.850916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14c246d6c7d7'
down_revision: Union[str, None] = '73f78a8350d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('Courier', 'Self_pickup', name='order_delivery').create(op.get_bind())
    op.add_column('orders', sa.Column('order_delivery', postgresql.ENUM('Courier', 'Self_pickup', name='order_delivery', create_type=False), nullable=True))
    op.add_column('orders', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'order_delivery')
    sa.Enum('Courier', 'Self_pickup', name='order_delivery').drop(op.get_bind())
    # ### end Alembic commands ###
