"""Add status column to carts table

Revision ID: 17844fd1f9a9
Revises: 3aeed9630d86
Create Date: 2024-12-03 19:10:22.939256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17844fd1f9a9'
down_revision: Union[str, None] = '3aeed9630d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('status', sa.Enum('Not_orded', 'Checkout', 'Completed', name='cart_status'), nullable=True))
    op.drop_column('carts', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('value', postgresql.ENUM('Not_orded', 'Checkout', 'Completed', name='cart_status'), autoincrement=False, nullable=True))
    op.drop_column('carts', 'status')
    # ### end Alembic commands ###
