"""Fix quanitity to quantity(2)

Revision ID: 278ed8d3aa01
Revises: c361c290c3a5
Create Date: 2024-12-03 19:19:32.505742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278ed8d3aa01'
down_revision: Union[str, None] = 'c361c290c3a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('order_items', 'quanitity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('quanitity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'quantity')
    # ### end Alembic commands ###
