"""Add quantity to order_item

Revision ID: 722ff2a61e1d
Revises: 17844fd1f9a9
Create Date: 2024-12-03 19:17:21.911001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722ff2a61e1d'
down_revision: Union[str, None] = '17844fd1f9a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('quanitity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'quanitity')
    # ### end Alembic commands ###
