"""total_price gone

Revision ID: 73f78a8350d4
Revises: 54e3cc8632f4
Create Date: 2025-01-20 02:28:10.813273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f78a8350d4'
down_revision: Union[str, None] = '54e3cc8632f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'total_price')
    op.drop_column('orders', 'total_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('carts', sa.Column('total_price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
