"""Fix quanitity to quantity

Revision ID: c361c290c3a5
Revises: 722ff2a61e1d
Create Date: 2024-12-03 19:18:31.434634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c361c290c3a5'
down_revision: Union[str, None] = '722ff2a61e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
